-- =============================================================================
-- Idea to Expo — MySQL schema + defaults
--
-- Target: MySQL 8.0.16+ (developed and tested on MySQL 9.1). Uses CHECK
-- constraints, JSON columns, expression defaults and generated columns.
--
-- Import (creates the database `idea_to_expo` if it does not exist):
--     mysql -u root -p < database/idea_to_expo.sql
-- or in MySQL Workbench: File → Run SQL Script…
--
-- Re-running is safe: every table is created with IF NOT EXISTS and the
-- default rows are only inserted when missing. It never drops anything.
--
-- All timestamps are UTC (the app sets `time_zone = '+00:00'` per connection).
-- Rows are keyed by UUID strings generated by the application; the DEFAULT
-- (UUID()) is only a convenience for manual inserts.
-- =============================================================================

CREATE DATABASE IF NOT EXISTS `idea_to_expo`
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `idea_to_expo`;

SET NAMES utf8mb4;

-- ---------------------------------------------------------------------------
-- Accounts & sessions (replaces Supabase Auth)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS `users` (
  `id`             CHAR(36)     NOT NULL DEFAULT (UUID()),
  `email`          VARCHAR(255) NOT NULL,
  `password_hash`  VARCHAR(255) NOT NULL,
  `role`           ENUM('ADMIN','EVALUATOR') NOT NULL,
  `full_name`      VARCHAR(200) NULL,
  `is_active`      TINYINT(1)   NOT NULL DEFAULT 1,
  `last_login_at`  DATETIME(3)  NULL,
  `created_at`     DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`     DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_users_email` (`email`),
  CONSTRAINT `chk_users_email_lower` CHECK (BINARY `email` = BINARY LOWER(`email`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- The cookie holds a random token; only its SHA-256 hash is stored here.
CREATE TABLE IF NOT EXISTS `sessions` (
  `id`            CHAR(64)     NOT NULL,
  `user_id`       CHAR(36)     NOT NULL,
  `expires_at`    DATETIME(3)  NOT NULL,
  `created_at`    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `last_seen_at`  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `ip`            VARCHAR(64)  NULL,
  `user_agent`    VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  KEY `ix_sessions_user` (`user_id`),
  KEY `ix_sessions_expires` (`expires_at`),
  CONSTRAINT `fk_sessions_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- Settings (single row, id = 1)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS `app_settings` (
  `id`                  TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `event_status`        ENUM('NOT_STARTED','LIVE','PAUSED','CLOSED') NOT NULL DEFAULT 'NOT_STARTED',
  -- When on, evaluators may revise a submitted evaluation while the event is LIVE.
  `allow_resubmission`  TINYINT(1)   NOT NULL DEFAULT 0,
  -- Ordered tie-break rule ids, interpreted by lib/results/ranking.ts.
  `tie_breakers`        JSON         NOT NULL DEFAULT (JSON_ARRAY()),
  -- Problem statement form header -> portal field mapping (lib/forms/mapping.ts).
  `form_field_mapping`  JSON         NOT NULL DEFAULT (JSON_OBJECT()),
  -- {"total_header": "...", "evaluator_header": "...", "domains_header": "..."}
  `sheet_writeback`     JSON         NOT NULL DEFAULT (JSON_OBJECT()),
  `updated_at`          DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `updated_by`          CHAR(36)     NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `chk_app_settings_singleton` CHECK (`id` = 1),
  CONSTRAINT `fk_app_settings_user` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `app_settings` (`id`) VALUES (1) ON DUPLICATE KEY UPDATE `id` = `id`;

-- ---------------------------------------------------------------------------
-- Students (CSV master data) and their problem statement submission
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS `students` (
  `id`                  CHAR(36)     NOT NULL DEFAULT (UUID()),
  -- Upper-case, no whitespace; the unique student identifier.
  `register_number`     VARCHAR(64)  NOT NULL,
  `name`                VARCHAR(255) NOT NULL,
  `gender`              VARCHAR(30)  NULL,
  `department`          VARCHAR(120) NULL,
  `year`                TINYINT UNSIGNED NULL,
  `section`             VARCHAR(30)  NULL,
  `email`               VARCHAR(255) NULL,
  `phone`               VARCHAR(40)  NULL,
  `status`              ENUM('ACTIVE','WITHDRAWN','DISQUALIFIED') NOT NULL DEFAULT 'ACTIVE',
  `source`              ENUM('FORM','IMPORT','MANUAL','SEED') NOT NULL DEFAULT 'IMPORT',
  `form_submitted_at`   DATETIME(3)  NULL,
  -- Optional admin-defined tie-break (lower wins), used by ADMIN_PRIORITY_ASC.
  `tie_break_priority`  INT          NULL,
  `created_at`          DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`          DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_students_register_number` (`register_number`),
  UNIQUE KEY `uq_students_email` (`email`),
  KEY `ix_students_department` (`department`),
  KEY `ix_students_status` (`status`),
  KEY `ix_students_name` (`name`),
  CONSTRAINT `chk_students_register_number` CHECK (
    `register_number` <> '' AND `register_number` NOT REGEXP '[[:space:]]'
    AND BINARY `register_number` = BINARY UPPER(`register_number`)),
  CONSTRAINT `chk_students_email_lower` CHECK (`email` IS NULL OR BINARY `email` = BINARY LOWER(`email`)),
  CONSTRAINT `chk_students_year` CHECK (`year` IS NULL OR `year` BETWEEN 1 AND 6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- One submission per student today. The FK lives here (not on students), so
-- moving to multiple projects/teams later only means dropping the unique key.
CREATE TABLE IF NOT EXISTS `ideas` (
  `id`                 CHAR(36)      NOT NULL DEFAULT (UUID()),
  `student_id`         CHAR(36)      NOT NULL,
  `problem_statement`  MEDIUMTEXT    NULL,
  `abstract`           MEDIUMTEXT    NULL,
  `ppt_url`            VARCHAR(2048) NULL,
  `other_details`      JSON          NOT NULL DEFAULT (JSON_OBJECT()),
  `submission_status`  ENUM('SUBMITTED','INCOMPLETE') NOT NULL DEFAULT 'SUBMITTED',
  `submitted_at`       DATETIME(3)   NULL,
  -- Row number of the latest response in the problem statement sheet.
  `response_row`       INT           NULL,
  -- How the form response was linked to the student record.
  `matched_by`         ENUM('REGISTER_NUMBER','EMAIL','CREATED') NOT NULL DEFAULT 'REGISTER_NUMBER',
  `created_at`         DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`         DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ideas_student` (`student_id`),
  CONSTRAINT `fk_ideas_student` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- Evaluators. There is NO limit on how many students an evaluator can take.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS `evaluators` (
  `id`           CHAR(36)     NOT NULL DEFAULT (UUID()),
  `user_id`      CHAR(36)     NULL,
  `name`         VARCHAR(200) NOT NULL,
  `email`        VARCHAR(255) NOT NULL,
  `employee_id`  VARCHAR(50)  NULL,
  `department`   VARCHAR(120) NULL,
  `status`       ENUM('ACTIVE','DISABLED') NOT NULL DEFAULT 'ACTIVE',
  `created_at`   DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`   DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_evaluators_user` (`user_id`),
  UNIQUE KEY `uq_evaluators_email` (`email`),
  UNIQUE KEY `uq_evaluators_employee` (`employee_id`),
  KEY `ix_evaluators_status` (`status`),
  CONSTRAINT `chk_evaluators_email_lower` CHECK (BINARY `email` = BINARY LOWER(`email`)),
  CONSTRAINT `fk_evaluators_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- Evaluation criteria and domains (admin-defined)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS `evaluation_criteria` (
  `id`            CHAR(36)     NOT NULL DEFAULT (UUID()),
  `name`          VARCHAR(120) NOT NULL,
  `description`   VARCHAR(1000) NULL,
  `max_marks`     SMALLINT UNSIGNED NOT NULL,
  `input_style`   ENUM('STARS','SLIDER','NUMBER') NOT NULL DEFAULT 'SLIDER',
  `sort_order`    INT          NOT NULL DEFAULT 0,
  `is_active`     TINYINT(1)   NOT NULL DEFAULT 1,
  -- Header of the score column in the problem statement sheet (defaults to name).
  `sheet_column`  VARCHAR(200) NULL,
  `created_at`    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_criteria_name` (`name`),
  CONSTRAINT `chk_criteria_max` CHECK (`max_marks` BETWEEN 1 AND 100),
  CONSTRAINT `chk_criteria_stars` CHECK (`input_style` <> 'STARS' OR `max_marks` <= 10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `domains` (
  `id`          CHAR(36)    NOT NULL DEFAULT (UUID()),
  `name`        VARCHAR(80) NOT NULL,
  `sort_order`  INT         NOT NULL DEFAULT 0,
  `is_active`   TINYINT(1)  NOT NULL DEFAULT 1,
  `created_at`  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_domains_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- Evaluations: ONE evaluator per student (unique student_id).
-- The first save claims the student; the row lock + this key make that safe
-- when two evaluators try at the same moment.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS `evaluations` (
  `id`            CHAR(36)    NOT NULL DEFAULT (UUID()),
  `student_id`    CHAR(36)    NOT NULL,
  `evaluator_id`  CHAR(36)    NOT NULL,
  `remarks`       TEXT        NULL,
  `status`        ENUM('IN_PROGRESS','COMPLETED') NOT NULL DEFAULT 'IN_PROGRESS',
  `version`       INT         NOT NULL DEFAULT 1,
  `total_score`   INT         NULL,
  `max_total`     INT         NULL,
  `started_at`    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `submitted_at`  DATETIME(3) NULL,
  `created_at`    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_evaluations_student` (`student_id`),
  KEY `ix_evaluations_evaluator` (`evaluator_id`, `status`),
  KEY `ix_evaluations_status` (`status`),
  CONSTRAINT `chk_evaluations_remarks` CHECK (`remarks` IS NULL OR CHAR_LENGTH(`remarks`) <= 5000),
  CONSTRAINT `chk_evaluations_completed` CHECK (
    `status` <> 'COMPLETED'
    OR (`total_score` IS NOT NULL AND `max_total` IS NOT NULL AND `submitted_at` IS NOT NULL)),
  CONSTRAINT `fk_evaluations_student` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_evaluations_evaluator` FOREIGN KEY (`evaluator_id`) REFERENCES `evaluators` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `evaluation_scores` (
  `evaluation_id`  CHAR(36) NOT NULL,
  `criterion_id`   CHAR(36) NOT NULL,
  `score`          INT      NOT NULL,
  PRIMARY KEY (`evaluation_id`, `criterion_id`),
  KEY `ix_scores_criterion` (`criterion_id`),
  CONSTRAINT `chk_scores_nonneg` CHECK (`score` >= 0),
  CONSTRAINT `fk_scores_evaluation` FOREIGN KEY (`evaluation_id`) REFERENCES `evaluations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_scores_criterion` FOREIGN KEY (`criterion_id`) REFERENCES `evaluation_criteria` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `evaluation_domains` (
  `evaluation_id`  CHAR(36) NOT NULL,
  `domain_id`      CHAR(36) NOT NULL,
  PRIMARY KEY (`evaluation_id`, `domain_id`),
  KEY `ix_eval_domains_domain` (`domain_id`),
  CONSTRAINT `fk_eval_domains_evaluation` FOREIGN KEY (`evaluation_id`) REFERENCES `evaluations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_eval_domains_domain` FOREIGN KEY (`domain_id`) REFERENCES `domains` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- Audit log, Google Sheets sync queue, locks, form sync runs
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS `audit_logs` (
  `id`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id`      CHAR(36)     NULL,
  `action`       VARCHAR(100) NOT NULL,
  `entity_type`  VARCHAR(60)  NULL,
  `entity_id`    VARCHAR(64)  NULL,
  `metadata`     JSON         NOT NULL DEFAULT (JSON_OBJECT()),
  `created_at`   DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `ix_audit_created` (`created_at`),
  KEY `ix_audit_action` (`action`, `created_at`),
  CONSTRAINT `fk_audit_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Coalescing: `pending_key` is non-NULL only while a job is PENDING, so the
-- unique key allows at most ONE pending job per entity. A job that is already
-- PROCESSING does not block a new PENDING one, so a change made while the
-- worker is mid-flight is never lost.
CREATE TABLE IF NOT EXISTS `sheet_sync_queue` (
  `id`             CHAR(36)    NOT NULL DEFAULT (UUID()),
  `entity_type`    ENUM('STUDENT','EVALUATOR','EVALUATION','RESULTS','RESPONSE_ROW') NOT NULL,
  `entity_id`      CHAR(36)    NOT NULL,
  `status`         ENUM('PENDING','PROCESSING','SUCCESS','FAILED','SUPERSEDED') NOT NULL DEFAULT 'PENDING',
  `attempts`       INT         NOT NULL DEFAULT 0,
  `last_error`     TEXT        NULL,
  `next_retry_at`  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `locked_at`      DATETIME(3) NULL,
  `created_at`     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `processed_at`   DATETIME(3) NULL,
  `pending_key`    VARCHAR(80) GENERATED ALWAYS AS (
                     IF(`status` = 'PENDING', CONCAT(`entity_type`, ':', `entity_id`), NULL)) VIRTUAL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sync_pending` (`pending_key`),
  KEY `ix_sync_claim` (`status`, `next_retry_at`),
  KEY `ix_sync_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sync_locks` (
  `name`         VARCHAR(60) NOT NULL,
  `holder`       VARCHAR(64) NULL,
  `lease_until`  DATETIME(3) NOT NULL DEFAULT '1970-01-01 00:00:00.000',
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `form_sync_runs` (
  `id`            CHAR(36)    NOT NULL DEFAULT (UUID()),
  `source`        ENUM('APPS_SCRIPT','SHEETS_PULL','CSV_IMPORT') NOT NULL,
  `status`        ENUM('SUCCESS','PARTIAL','FAILED') NOT NULL,
  `received`      INT         NOT NULL DEFAULT 0,
  `inserted`      INT         NOT NULL DEFAULT 0,
  `updated`       INT         NOT NULL DEFAULT 0,
  `unchanged`     INT         NOT NULL DEFAULT 0,
  `skipped`       INT         NOT NULL DEFAULT 0,
  `errors`        JSON        NOT NULL DEFAULT (JSON_ARRAY()),
  `triggered_by`  CHAR(36)    NULL,
  `created_at`    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `ix_form_runs_created` (`created_at`),
  CONSTRAINT `fk_form_runs_user` FOREIGN KEY (`triggered_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
